////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./regdefs.h
//
// Project:	OpenArty, an entirely open SoC based upon the Arty platform
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga autofpga -d -o . allclocks.txt global.txt icape.txt version.txt buserr.txt pic.txt pwrcount.txt spio.txt clrspio.txt rtcgps.txt rtcdate.txt wbuconsole.txt bkram.txt spansion.txt sdram.txt zipmaster.txt mdio.txt enet.txt mem_flash_bkram.txt mem_bkram_only.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2017-2020, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
#ifndef	REGDEFS_H
#define	REGDEFS_H


//
// The @REGDEFS.H.INCLUDE tag
//
// @REGDEFS.H.INCLUDE for masters
// @REGDEFS.H.INCLUDE for peripherals
// And finally any master REGDEFS.H.INCLUDE tags
// End of definitions from REGDEFS.H.INCLUDE


//
// Register address definitions, from @REGS.#d
//
// FLASH erase/program configuration registers
#define	R_FLASHCFG      	0x02000000	// 02000000, wbregs names: FLASHCFG, QSPIC
// CONSOLE registers
#define	R_CONSOLE_FIFO  	0x04000004	// 04000000, wbregs names: UFIFO
#define	R_CONSOLE_UARTRX	0x04000008	// 04000000, wbregs names: RX
#define	R_CONSOLE_UARTTX	0x0400000c	// 04000000, wbregs names: TX
// FPGA CONFIG REGISTERS: 0x4e0-0x4ff
#define	R_CFG_CRC       	0x06000000	// 06000000, wbregs names: FPGACRC
#define	R_CFG_FAR       	0x06000004	// 06000000, wbregs names: FPGAFAR
#define	R_CFG_FDRI      	0x06000008	// 06000000, wbregs names: FPGAFDRI
#define	R_CFG_FDRO      	0x0600000c	// 06000000, wbregs names: FPGAFDRO
#define	R_CFG_CMD       	0x06000010	// 06000000, wbregs names: FPGACMD
#define	R_CFG_CTL0      	0x06000014	// 06000000, wbregs names: FPGACTL0
#define	R_CFG_MASK      	0x06000018	// 06000000, wbregs names: FPGAMASK
#define	R_CFG_STAT      	0x0600001c	// 06000000, wbregs names: FPGASTAT
#define	R_CFG_LOUT      	0x06000020	// 06000000, wbregs names: FPGALOUT
#define	R_CFG_COR0      	0x06000024	// 06000000, wbregs names: FPGACOR0
#define	R_CFG_MFWR      	0x06000028	// 06000000, wbregs names: FPGAMFWR
#define	R_CFG_CBC       	0x0600002c	// 06000000, wbregs names: FPGACBC
#define	R_CFG_IDCODE    	0x06000030	// 06000000, wbregs names: FPGAIDCODE
#define	R_CFG_AXSS      	0x06000034	// 06000000, wbregs names: FPGAAXSS
#define	R_CFG_COR1      	0x06000038	// 06000000, wbregs names: FPGACOR1
#define	R_CFG_WBSTAR    	0x06000040	// 06000000, wbregs names: WBSTAR
#define	R_CFG_TIMER     	0x06000044	// 06000000, wbregs names: CFGTIMER
#define	R_CFG_BOOTSTS   	0x06000058	// 06000000, wbregs names: BOOTSTS
#define	R_CFG_CTL1      	0x06000060	// 06000000, wbregs names: FPGACTL1
#define	R_CFG_BSPI      	0x0600007c	// 06000000, wbregs names: FPGABSPI
// Ethernet configuration (MDIO) port
#define	R_MDIO_BMCR     	0x08000000	// 08000000, wbregs names: BMCR
#define	R_MDIO_BMSR     	0x08000004	// 08000000, wbregs names: BMSR
#define	R_MDIO_PHYIDR1  	0x08000008	// 08000000, wbregs names: PHYIDR1
#define	R_MDIO_PHYIDR2  	0x0800000c	// 08000000, wbregs names: PHYIDR2
#define	R_MDIO_ANAR     	0x08000010	// 08000000, wbregs names: ANAR
#define	R_MDIO_ANLPAR   	0x08000014	// 08000000, wbregs names: ANLPAR
#define	R_MDIO_ANER     	0x08000018	// 08000000, wbregs names: ANER
#define	R_MDIO_ANNPTR   	0x0800001c	// 08000000, wbregs names: ANNPTR
#define	R_MDIO_PHYSTS   	0x08000040	// 08000000, wbregs names: PHYSYTS
#define	R_MDIO_FCSCR    	0x08000050	// 08000000, wbregs names: FCSCR
#define	R_MDIO_RECR     	0x08000054	// 08000000, wbregs names: RECR
#define	R_MDIO_PCSR     	0x08000058	// 08000000, wbregs names: PCSR
#define	R_MDIO_RBR      	0x0800005c	// 08000000, wbregs names: RBR
#define	R_MDIO_LEDCR    	0x08000060	// 08000000, wbregs names: LEDCR
#define	R_MDIO_PHYCR    	0x08000064	// 08000000, wbregs names: PHYCR
#define	R_MDIO_BTSCR    	0x08000068	// 08000000, wbregs names: BTSCR
#define	R_MDIO_CDCTRL   	0x0800006c	// 08000000, wbregs names: CDCTRL
#define	R_MDIO_EDCR     	0x08000074	// 08000000, wbregs names: EDCR
#define	R_CLRLED        	0x0a000000	// 0a000000, wbregs names: CLRLED
#define	R_CLRLED0       	0x0a000000	// 0a000000, wbregs names: CLRLED0, CLR0
#define	R_CLRLED1       	0x0a000004	// 0a000000, wbregs names: CLRLED1, CLR1
#define	R_CLRLED2       	0x0a000008	// 0a000000, wbregs names: CLRLED2, CLR2
#define	R_CLRLED3       	0x0a00000c	// 0a000000, wbregs names: CLRLED3, CLR3
#define	R_NET_RXCMD     	0x0a000020	// 0a000020, wbregs names: RXCMD, NETRX
#define	R_NET_TXCMD     	0x0a000024	// 0a000020, wbregs names: TXCMD, NETTX
#define	R_NET_MACHI     	0x0a000028	// 0a000020, wbregs names: MACHI
#define	R_NET_MACLO     	0x0a00002c	// 0a000020, wbregs names: MACLO
#define	R_NET_RXMISS    	0x0a000030	// 0a000020, wbregs names: NETMISS
#define	R_NET_RXERR     	0x0a000034	// 0a000020, wbregs names: NETERR
#define	R_NET_RXCRC     	0x0a000038	// 0a000020, wbregs names: NETCRCERR
#define	R_NET_TXCOL     	0x0a00003c	// 0a000020, wbregs names: NETCOL
// RTC clock registers
#define	R_CLOCK         	0x0a000040	// 0a000040, wbregs names: CLOCK
#define	R_TIMER         	0x0a000044	// 0a000040, wbregs names: TIMER
#define	R_STOPWATCH     	0x0a000048	// 0a000040, wbregs names: STOPWATCH
#define	R_CKALARM       	0x0a00004c	// 0a000040, wbregs names: ALARM, CKALARM
#define	R_BUILDTIME     	0x0a000060	// 0a000060, wbregs names: BUILDTIME
#define	R_BUSERR        	0x0a000064	// 0a000064, wbregs names: BUSERR
#define	R_PIC           	0x0a000068	// 0a000068, wbregs names: PIC
#define	R_PWRCOUNT      	0x0a00006c	// 0a00006c, wbregs names: PWRCOUNT
#define	R_RTCDATE       	0x0a000070	// 0a000070, wbregs names: RTCDATE, DATE
#define	R_SPIO          	0x0a000074	// 0a000074, wbregs names: SPIO
// A register capturing subseconds, locked to GPS if present
#define	R_SUBSECONDS    	0x0a000078	// 0a000078, wbregs names: SUBSECONDS
#define	R_VERSION       	0x0a00007c	// 0a00007c, wbregs names: VERSION
#define	R_NET_RXBUF     	0x0c000000	// 0c000000, wbregs names: NETRXB
#define	R_NET_TXBUF     	0x0c001000	// 0c000000, wbregs names: NETTXB
#define	R_BKRAM         	0x0e000000	// 0e000000, wbregs names: RAM
#define	R_FLASH         	0x10000000	// 10000000, wbregs names: FLASH
#define	R_SDRAM         	0x20000000	// 20000000, wbregs names: SDRAM


//
// The @REGDEFS.H.DEFNS tag
//
// @REGDEFS.H.DEFNS for masters
#define	ENETCLKFREQHZ 25000000
#define	R_ZIPCTRL	0x40000000
#define	R_ZIPDATA	0x40000004
// #define	RESET_ADDRESS	@$[0x%08x](RESET_ADDRESS)
#define	BAUDRATE	1000000
#define	CLKFREQHZ 82500000
// @REGDEFS.H.DEFNS for peripherals
#define	SDRAMBASE	0x20000000
#define	SDRAMLEN	0x10000000
#define	FLASHBASE	0x10000000
#define	FLASHLEN	0x01000000
#define	FLASHLGLEN	24
//
#define	FLASH_RDDELAY	3
#define	FLASH_NDUMMY	6
//
#define	BKRAMBASE	0x0e000000
#define	BKRAMLEN	0x00010000
// @REGDEFS.H.DEFNS at the top level
// End of definitions from REGDEFS.H.DEFNS
//
// The @REGDEFS.H.INSERT tag
//
// @REGDEFS.H.INSERT for masters
// @REGDEFS.H.INSERT for peripherals

#define	CPU_GO		0x0000
#define	CPU_RESET	0x0040
#define	CPU_INT		0x0080
#define	CPU_STEP	0x0100
#define	CPU_STALL	0x0200
#define	CPU_HALT	0x0400
#define	CPU_CLRCACHE	0x0800
#define	CPU_sR0		0x0000
#define	CPU_sSP		0x000d
#define	CPU_sCC		0x000e
#define	CPU_sPC		0x000f
#define	CPU_uR0		0x0010
#define	CPU_uSP		0x001d
#define	CPU_uCC		0x001e
#define	CPU_uPC		0x001f

#ifdef	BKROM_ACCESS
#define	RESET_ADDRESS	@$[0x%08x](bkrom.REGBASE)
#else
#ifdef	FLASH_ACCESS
#define	RESET_ADDRESS	0x10400000
#else
#define	RESET_ADDRESS	0x0e000000
#endif	// FLASH_ACCESS
#endif	// BKROM_ACCESS


// Flash control constants
#define	QSPI_FLASH	// This core and hardware support a Quad SPI flash
#define	SZPAGEB		256
#define	PGLENB		256
#define	SZPAGEW		64
#define	PGLENW		64
#define	NPAGES		256
#define	SECTORSZB	(NPAGES * SZPAGEB)	// In bytes, not words!!
#define	SECTORSZW	(NPAGES * SZPAGEW)	// In words
#define	NSECTORS	64
#define	SECTOROF(A)	((A) & (-1<<16))
#define	SUBSECTOROF(A)	((A) & (-1<<12))
#define	PAGEOF(A)	((A) & (-1<<8))

// @REGDEFS.H.INSERT from the top level
typedef	struct {
	unsigned	m_addr;
	const char	*m_name;
} REGNAME;

extern	const	REGNAME	*bregs;
extern	const	int	NREGS;
// #define	NREGS	(sizeof(bregs)/sizeof(bregs[0]))

extern	unsigned	addrdecode(const char *v);
extern	const	char *addrname(const unsigned v);
// End of definitions from REGDEFS.H.INSERT


#endif	// REGDEFS_H
